name: TranslateThis
on:
    push:
        branches:
            - main
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Install Composer Dependencies
              working-directory: ./app
              run: composer install --prefer-dist
            - name: Run Tests
              working-directory: ./app
              run: composer run-phpunit
            - run: docker build --target app -t chidodesigns/docker-php-template:1.0 -f ./php/Dockerfile .
            - run: docker build -t chidodesigns/nginx-php:1.0 -f ./nginx/Dockerfile .
            - name: Log in to Docker Hub
              uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
              with:
                username: ${{ secrets.DOCKER_USERNAME }}
                password: ${{ secrets.DOCKER_PASSWORD }}
            - run: docker push chidodesigns/docker-php-template:1.0
            - run: docker push chidodesigns/nginx-php:1.0